#' Cleaned IDEA Study Clinical Data With Derived Fields
#'
#' A record for each patients enrolled on the study.
#' Note that not all tests are recorded but only the most recent/used for diagnosis.
#' Dates are mostly unreliable.
#'
#' @format A data frame with 769 rows and 221 variables:
#' \describe{
#'   \item{CtryBirth}
#'   \item{SiteID}
#'   \item{Ethn}
#'   \item{PatientStudyID}
#'   \item{Cough}
#'   \item{Fever}
#'   \item{Ngtsweat}
#'   \item{Wghtloss}
#'   \item{Haemop}
#'   \item{Leth}
#'   \item{OtherAE1}
#'   \item{OtherAE2}
#'   \item{OtherAE3}
#'   \item{OtherAE4}
#'   \item{OtherAE5}
#'   \item{OtherAE6}
#'   \item{TBdrug1Start}
#'   \item{TBdrug2Start}
#'   \item{TBdrug3Start}
#'   \item{TBdrug4Start}
#'   \item{TBdrug5Start}
#'   \item{TBdrug6Start}
#'   \item{TBDrug1End}
#'   \item{TBDrug2End}
#'   \item{TBDrug3End}
#'   \item{TBDrug4End}
#'   \item{TBDrug5End}
#'   \item{TBDrug6End}
#'   \item{TBtreatdur}
#'   \item{CoughEnd}
#'   \item{FeverEnd}
#'   \item{NgtsweatEnd}
#'   \item{WghtlossEnd}
#'   \item{HaemopEnd}
#'   \item{LethEnd}
#'   \item{OtherAE1End}
#'   \item{OtherAE2End}
#'   \item{OtherAE3End}
#'   \item{OtherAE4End}
#'   \item{OtherAE5End}
#'   \item{OtherAE6End}
#'   \item{MeansFinDiagother.multiple}
#'   \item{VisitFU}
#'   \item{DateVisitFU}
#'   \item{DateConsent}
#'   \item{PatientAge}
#'   \item{Sex}
#'   \item{EntryUK}
#'   \item{HIVpos}
#'   \item{PrevBCG}
#'   \item{TBcont}
#'   \item{CurrHomeless}
#'   \item{Diagoutcome}
#'   \item{DateDiagCon}
#'   \item{MeansFinDiag1}
#'   \item{Dosanjh}
#'   \item{QFNtestDate}
#'   \item{QFN}
#'   \item{TSPOTtestDate}
#'   \item{TSPOT}
#'   \item{TSTtestDate}
#'   \item{TST}
#'   \item{TypeSmear}
#'   \item{SmeartestDate}
#'   \item{Smear}
#'   \item{TBculttest}
#'   \item{TBcultsite}
#'   \item{TBculttestDate}
#'   \item{TBcult}
#'   \item{TBcultReportRec}
#'   \item{CSFtestDate}
#'   \item{CSF}
#'   \item{BALtestDate}
#'   \item{BAL}
#'   \item{HistBioptestDate}
#'   \item{HistBiop}
#'   \item{NeedleAsptestDate}
#'   \item{NeedleAsp}
#'   \item{PCRtestDate}
#'   \item{PCR}
#'   \item{CXRtestDate}
#'   \item{CXR}
#'   \item{CTtestDate}
#'   \item{CT}
#'   \item{MRItestDate}
#'   \item{MRI}
#'   \item{Othertest1Name}
#'   \item{Othertest1Date}
#'   \item{Othertest1Res}
#'   \item{Othertest2Name}
#'   \item{Othertest2Date}
#'   \item{Othertest2Res}
#'   \item{Exclude}
#'   \item{PatientSet}
#'   \item{EPTBorPTB}
#'   \item{Diagnostic_mean}
#'   \item{Bodysite_smear}
#'   \item{Bodysite_culture}
#'   \item{New_occupation}
#'   ...
#' }
#' @source \url{}
"data"
